### PR TITLE
WIP added support for package based installation sonar and sonar-scanner

### PR DESCRIPTION
**Pull request by witjoh**
- needs testing
- needs adding rspec (a lot)

Already did a PR for commenting.

testing in the progess, and rspec will be added shortly

### CODE REVIEW

**Comment by mmarseglia** [comment]
thanks for this update.  it was sorely needed.  when would you like to merge this in?

**Comment by witjoh** [comment]
Running the tests on redhat tomorrow,  and then i will add more puppet rspec.  I will also rewrite the existing ones to the new syntax while I'm doing that, it is not that much.  Need just a couple of days, and then I will update this PR.

**Comment by witjoh** [comment]
Just a quick status .....

Did some installation test both from zip and package on centos 6.7, 7,1 and 7.2.  On centos7, It does install, but it takes more then 10 minutes till the webgui becomes available.  But cant find the reason why ....
from the logs : 
2016.05.17 14:40:08 INFO  web[jruby.rack] using a shared (threadsafe!) runtime
2016.05.17 14:40:14 INFO  web[jruby.rack] keeping custom (config.logger) Rails logger instance
2016.05.17 14:49:12 INFO  web[o.a.c.u.SessionIdGeneratorBase] Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [537,505] milliseconds.
2016.05.17 14:49:12 INFO  web[o.s.s.p.MasterServletFilter] Initializing servlet filter org.sonar.server.authentication.InitFilter@4b1b4a49 [pattern=/sessions/init/*]

Start testing the installation of the sonar-scanner now.

**Comment by mmarseglia** [comment]
I haven't found anything as to why it would delay on centos7.

**Comment by witjoh** [comment]
At least we have the beginning of working rspec-puppet and travis, for 3.x and 4.x version (except 4.5).
And a good resource coverage.  Only for ruby version 2.0.0 at the moment.  
In the mean time, I made this PR a really big mess :(

I should clean this up and split it in smaller ones covering just one change.

**Comment by witjoh** [comment]
@mmarseglia 
Seems to me this messy PR is done...
Still some problems with travis and puppet 4.  The code does work on puppet4, but hiera > 3.1 does not work well with rspec-puppet.
https://tickets.puppetlabs.com/browse/HI-505
none of my ties to solve this by pinning hiera to a version lower then 3.1 has any success.  
But at least now this module has a much better rspec testing coverage.

Should this be a good idea to push this all upstream ?

**Comment by mmarseglia** [comment]
Thank you very much for the PR.  I plan to update the Gemfile, Rakefile and .travis-ci.yml shortly, so we will see if those problems go away.

**Pull request merged**
